### ISSUE TITLE
Congrats on a super cool game! 🤓

### ISSUE THREAD

**Issue by ahallora** [bencoder/js13k-2019#12]
Hi Ben and Salvatore,

Congratulations on winning js13k 2019! I too really enjoyed your game and was disappointed after completing the memory core! As a code golf with an high handicap still I looked at your code and noticed that you were using a lot of characters on random unimportant stuff, like `pressed`, `momentary`, `targets`and so on... Variables that (in the name of the game) could be reduced to a single char making room for perhaps a level 7 or 8... 😁🙈

Anyways, I just did a quick calculation of the potential saving of changing e.g. `{pressed: 1}` to `{p: 1}` and just by a super quick overview I found a bunch of variables that could be reduced in length to save those sweet sweet bytes...

My calculation shows a **reduction of 0,8 kB (6,4%)**! - Just consider how much more you could _golf it_ and how many more levels you could have added to further cement your victory!? 🤓

Was this something you considered during development? 

```javascript
arr = [
    { text: "pressed", count: 24 },
    { text: "momentary", count: 22 },
    { text: "start", count: 8 },
    { text: "targets", count: 23 },
    { text: "type", count: 23 },
    { text: "walls", count: 8 },
    { text: "doors", count: 8 },
    { text: "switches", count: 8 },
    { text: "polygon", count: 8 },
    { text: "playerLightPosition", count: 6 }
];
saved = arr
    .map(x => Array(x.count).fill(x.text).join("").length - x.count)
    .reduce((x, y) => x + y) / 1000;

console.log(`${saved} kB potential saving ~ ${(saved/13 * 100).toFixed(2)}% reduction`);
```

Looking forward to your entry for 2020! 😉

**Comment by bencoder** [comment]
Hi Ahallora,

Thanks for the kind comments and the analysis!

Yes we definitely did consider it, and had it in mind (as well as many other size optimizations) for if we ever started getting close to the limit - but we never did. Time was a much bigger constraint for us than the 13k limit this year.

I think though that the savings wouldn't be so large as the 13kb limit is after zipping, and I expect the zip process optimises out most of the repetition on the text, but it would definitely be interesting to find out if you want to try implementing the changes :D

I'm also looking forward to next year! Will you enter / have you entered?

**Comment by ahallora** [comment]
Cool, thanks for elaborating. 😄I'll just leave it here, because you're probably right about the zip process optimizations... 

And no, I'm not planning on participating in js13k. I'm simply not that skilled a programmer to pursue such an endeavour; but kudos for those that do. 👍
